### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by K2AAE** [sp9bsl/UHSDR#3]
// New lcd defines, ONLY ONE MAY BE SET AT COMPILE TIME 
 
// ALTERNATIVE GROUP START USE_GFX 
#define USE_GFX_ILI9486 
//#define USE_DRIVER_RA8875 
//#define USE_GFX_ILI932x 
// ALTERNATIVE GROUP END USE_GFX 
 
Kind of kills automation to hand edit.
Could do a diff grep thingie but I've forgotten most of that 'stuff'

**Comment by db4ple** [comment]
Yes, you're right. And this is going to be changed for exactly that reason.  But not tonight.

**Comment by sp9bsl** [comment]
Hi,
i'm still waiting for a brave person who will test things i did with:
#define USE_GFX_ILI9486
:-)

73 Slawek

**Comment by K2AAE** [comment]
The display I purchased for one mcHF has a ILI9488 YOR 2012, ILI9486 YOR 2010, the newer controller.
:-(

**Comment by sp9bsl** [comment]
ILI9488 is very similar to ILI9486. I think it should work but I didn't test it although. So, be the one who make the test please.

**Comment by K2AAE** [comment]
I wish; My mcHF "populated" boards arrived the other day, I had to place an order for parts at three distributors and still ordered $130 worth of parts from Ebay. My 'bare' boards are sitting there, I used them to get measurements and figure out what 'size' parts were needed since the BOM sucked. 
While looking up the controller of a new 3.5" display I purchased for a Arduino DUE I discovered: https://github.com/Bodmer/TFT_HX8357 He has some neat stuff on fonts and shows the difference between HX8357B, HX8357C, ILI9481, ILI9486.

**Comment by K2AAE** [comment]
While studying git I was wondering why my github git of USDR was behind by the number of days since I forked it. 
Found I had to:  git remote add upstream https://github.com/df8oe/UHSDR.git and then:
 git fetch upstream which brings all the changes that have happened since I forked to my local HD clone. When I looked at my git with GitKraken everything was back to sync. I don't know if this will impact you but I do know that most all the forks that are checked out are out of date or sync or whatever they call it. I added this to the wiki

**Comment by sp9bsl** [comment]
Hi,
no, that will not impact me because it is my repository and it is same or one step behind my local repo on HDD. I merge commits then I fetch changed repo to my local HDD by git. I don't use GitKraken.

73 Slawek

**Comment by K2AAE** [comment]
I still haven't figured out how the github fork gets updated, mine showed it was/is behind, on my local drive I fetched (using the command line) from df80e/UHSDR which updated my clone HD git but how do you update the github git? When I look at forked branches in df80e/UHSDR the github 'git' forks are mostly out of date except: db4ple - I suppose we should ask how he keeps his github git in sync.

**Comment by sp9bsl** [comment]
I just do commit and then push -f origin, and that's all. I think db4ple has knowledge how it works...

**Comment by K2AAE** [comment]
Github contacted me, seems in the Desktop Current branch drop down they list upstream/active-devel by selecting that as the current branch I can Fetch all changes from DF8OE to my Github fork git updating it to current, takes about 2 seconds. https://desktop.github.com/ if you use Windows a must and I believe the only means to update the files in a fork git when you're not doing pulls.

**Comment by sp9bsl** [comment]
Can I close this issue?
