### ISSUE TITLE
testing with adaptor

### ISSUE THREAD

**Issue by df8oe** [sp9bsl/UHSDR#5]
Hi Slawek,

I tried it with mcHF and OVI40 - but no luck. Both same behaviour: firmware starts, red LED lights, after a few seconds green LED lights, both stay lit for a few seconds, then red LED goes OFF. Screen always is blank, no spikes, no reaction. Firmware is running (Encoders and buttons do work).

At mcHF I have not changed anything - just build it using Makefile. For OVI40 I tried with SPI_DMA enabled and disabled - no difference.

Now there can be more than one problem.

- can it be a problem that newest bootloader initializes SPI?
- can it be that Makefile builds are not supportde yet?
- is it a hardware issue?

I have checked wiring double and more - everything as I wrote to you.

If it works at your mcHF: can you send me binary (best .dfu - but I can try .bin, too) via email?

73
Andreas

**Comment by df8oe** [comment]
Update:
Hardware issues.... One bad soldering on adaptor. Now screen initializes on reset on OVI40 and "white" is written with a darker grey - but no characters or graphics yet. mcHF I tested has not had touchscreen modification so no SPI signals on recent header pins . I have to do mod first... I will try tomorrow

**Comment by df8oe** [comment]
Update II:
I have done touchscreen mod on mcHF where I test new LCD - and...  SUCCESS!!

3.5" with adaptor does run on mcHF - but not on OVI40. So we do no longer have hardware error but software error... On OVI40 regardless if SPI_DMA is enabled or not following happens:

1) direct after power on bright blank screen
2) some milliseconds later I see LCD reset (complete screen changes at one time)
3) next screen is written from right to left with homogene, darker grey - but no characters.

**Comment by sp9bsl** [comment]
Hi Andreas,
Great! I forgot to say that all mods regarding lcd should be done because 3.5" raspberry lcd has lcd and touchpanel connecter to one SPI port.
About OVI40: i will check definitions again against any error in a moment. There should be something wrong with port definitions for f7.

**Comment by df8oe** [comment]
Hi Slawek,

of course mods must be done. It is a mcHF for repair - not mine. So I have forgotten to look if mod is present ;)

OVI40: may be. Or timing/speed? Touchscreen of course is implemented in OVI40 and LCD can/must use same SPI port.

**Comment by sp9bsl** [comment]
Yes, you can decrease speed of spi by changing SPI_BAUDRATE_PRESCALER_2 to _4 in 450 line of ui_lcd_hy28.c (in function UiLcdHy28_SpiInit) there is definition for USE_GFX_ILI_9486. This will tell us do the SPI runs too fast (but i think it can run at little faster in f7 also).

**Comment by sp9bsl** [comment]
Is the working lcd for OVI40 in parallel mode? I'm not shure but i see that only for mcHF is USE_DISPLAY_SPI defined (line 19 of ui_lcd_hy28.c). All other pin definitions looks ok.

**Comment by df8oe** [comment]
Hi Slawek,

you are right - that may be the problem!! OVI40 exclusively uses parallel mode... I will give it a try but not today. I am busy the whole day up to late night... And I will get a new 3.5" LCD and wire it parallel. We do not want to switch to SPI usage on OVI40 because of there are enough GPIOs available. I will order one LCD again and rewire it by unsoldering shift registers and logic and my adaptor PCB. It is the fastest method to get a parallel one :)

**Comment by sp9bsl** [comment]
Hi Andreas,

Ok, i will do it also in mcHF. Ihave second 3.5 for this test but i must design pcb for it first, there is too many wires in parallel mode and flat ribbon is very weak. Anyway, i'm happy that you have working one on mcHF. Is the size of items acceptable for you?

73 Slawek

**Comment by df8oe** [comment]
Yes - size is ok. But this is something we can take a look at later. I have done some investigations again so that we can go further faster...

I defined USE_SPI for OVI40 and tried a build with USE_SPI_DMA and one without. Of course it was wrong not to define USE_SPI for OVI40. With that LCD initializes. If USE_SPI_DMA is enabled it fails completely, and without that it begins to clear the screen vertically from upper side downwards - but gets stuck at ~3/4 of the screen and then turns white again. I think we must have SPI_DMA running because time for transferring data is too long and audio interrupt impacts transfer or something like this (?)

But I can state if USE_SPI is enabled LCD comes to life! Not completely running yet but we approach...

**Comment by sp9bsl** [comment]
I'm waiting for your pcb for OVI40 UI, so then i will be able to do something on F7. For now i can only watch it "theoretically". But i will try to help you.

**Comment by df8oe** [comment]
Success on OVI40!!

1) activate USE_DISPLAY_SPI
2) deactivate USE_SPI_DMA
3) set prescaler for SPI clock to 4 instead of 2

It works - but it is much slower as on mcHF (due to no DMA transfer).

:)

**Comment by sp9bsl** [comment]
Good! So we have speed limit there. I see that chinese 4094 must have limit far below Texas Instruments which can go up to 80MHz... So we'll go into parallel.

**Comment by df8oe** [comment]
Yes. But nothing to care about if we switch to parallel. But now I can go with you during tests.

**Comment by sp9bsl** [comment]
Andreas, look at [this](https://github.com/notro/fbtft/wiki/SPI-interface-circuit), it may help. The schematic is similar or the same like in our raspberry 3.5" lcd. I found it when i started my lcd upgrade work in may.
