### ISSUE TITLE
Yet Another Display?

### ISSUE THREAD

**Issue by K2AAE** [sp9bsl/UHSDR#7]
My Case arrived and there is no way a 3.5" display will fit unless I lose the bottom row of keys! Looking at the 3.2" display it 'might' fit with just milling to open the display hole. I have a 3.2" coming for a Arduino Due project I'll see if it will fit but I did find a source of 3.2" display for $7 + $5 for capacitive touch controller without shields. https://cdn-shop.adafruit.com/datasheets/HX8357-D_DS_April2012.pdf the down side is the controller: HX8753 appears to be a 948x clone? If you get a chance could you glance at the pdf? With the China case the only option will be building a custom shield that plugs into the UI board by using a display that doesn't have a shield, without the SPI touch it would be good.
FYI: The SPI touch in those displays use the SPI clock signal to do the conversion hence the slow speeds.   

Thanks

**Comment by sp9bsl** [comment]
Hi Kevin,
commands seems to be the same, but it will be best to test it with ili9486 firmware. At this moment we use XPT2046 for touch controlling (resistive type), it also uses SPI clock for ADC sampling and conversion, so we must slow down SPI when want to read from it. I think, but i'm not shure that RA8875 will have capacitive panel.

73 Slawek

**Comment by Harry-ei6ku** [comment]
Quick Question, is the 3.2" display you found 480 x 320??

Harry

**Comment by K2AAE** [comment]
Yes, for the Due https://goo.gl/Zdo84c and bare at buydisply is 240X320 https://goo.gl/SmD4UT
It appears the ebay 480X320 with the HX8753 could be removed from the shield it's on and placed on a shield the same as the mcHF display for replacement, I have one at the post office I'll be picking up tomorrow, I'll see if it will fit. At any case a 3.2 capacitive touch screen is $5
    
Why are you using serial on the mcHF? It has 16 data line going to it.
