### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by df8oe** [sp9bsl/UHSDR#8]
I fixed it. The panel I used for parallel rewiring does have another controller which is not 100% compatible to ILI9486. I soldered one of the panels which I tested using Arturs "repaired" adaptor PCB and it worked out-of-the-box on mcHF and OVI40.

I can confirm that speed is *tremendous* faster on OVI40 than on mcHF. I can confirm too that firmware which is built for OVI40 with "#define USE_SPI" works with 3.5" SPI *and* parallel in autodetection. So please add another #ifdef which includes in case of USE_ILI9486 USE_SPI. I do not want to do this in
active-devel branch because of incompatibility with active-devel-builds - we will fix that at merging your branch to active devel.

Driver implementation is finished now.

Now we can start to optimize screen layout. I forward this issue to db4ple and we should start discussion how to unify layout settings for different screen resolutions. We must discuss screen layout, too because we can show scope, waterfall AND text areas for digital modes simultaneously...

The first goodie you can start is to expand scope and waterfall to 480px - just for fun and showing possibilities of new LCD. I am not sure if it was your LCD implementation: I saw a waterfall/screen where filter bandwidth was shown in bright grey area in wf/scope instead of small bar under it....

I will investigate where we can get bare LCD panels possibly with optional parallel and SPI connection on panel. I have found three different interesting panels at aliexpress and will give them a try. Possibly we can design an plate where headers compatible for HY28 and HY32 are present, touchscreen controller on board and some 0R-jumpers to select parallel or SPI mode like on HY28. But that is my part ;)

73
Andreas

**Comment by sp9bsl** [comment]
Hi,
Strange but i didn't have notice that you sent mail to me and open this issue...
Anyway, I'm glad that it works, i hoped that it will work without problems on OVI40. In mcHF there is also very big difference in speed (OVI40 F7 runs only about 33% faster), although there is more i can do with code optimisation. Also we can decrease the speed of IO 'coz now we have GPIO_SPEED_FREQ_VERY_HIGH on FSMC.
I have almost finished and tested adapter board for lcd removed from Rpi lcd, but i will wait for new lcd type to place it on pcb and then send it to factory, i understood that your part is a choice of new lcd right? ;) I think this is good idea 'coz this one do not have full IM0...2 configuration pins, so it is impossible to choose SPI mode.

Yes i implemented the highlight for bandwidth on spectrum and i strongly want do it in new firmware so i will implement it (also adding some configuration options to DISPLAY menu). So this is the next step: expand the spectrum and add the highlight (waterfall will do it automatically).
Also i will move the freq ruler to top as you can see in my video, It is important to not have it below spectrum and separate the waterfall from scope with it.

I also changed the Travis file to save output files but i can't make it works correct. 

73 Slawek

**Comment by sp9bsl** [comment]
New feature added: bandwidth highlight. Should work for 320x240 display too.
Two more options added to display menu:
**Scope BW Trace Colour**  (just select one of the available colours for foreground of highlighted bandwidth)
**Scope BW BCKgr Colour** (select % of **Scope BW Trace Colour** in 10% steps for background)

73 Slawek

**Comment by sp9bsl** [comment]
Spectrum and waterfall enlarged to full width. Need testing now.
73 Slawek
